Implementation of Smith normal form method.
tda-pk/tda-pk pull request #39
Opened 2021-12-10 23:14 UTC by AxelsFirst

Added class of matrices, so that we can calculate Smith normal form of a matrix and it's rank.

2021-12-12 11:58 UTC, besiobu requested changes
Minor comments pertaining mainly to checking inputs parameters, examples and documentation.

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +        Entries have to be integers.
Add a condition to check if the input is a list of non-empty lists of integers. An exception should be raised if something other than lists of integers is passed.

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +    def get_col(self, col_index):
Verify that `0 <= col_index < self.num_cols`.

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +    def get_row(self, row_index):
Verify that `0 <= row_index < self.num_rows`.

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +    def change_row(self, row_index, values):
Verify that `0 <= row_index < self.num_rows`.
Verify that `len(values) == len(self.entries[0])`.

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +    def change_col(self, col_index, values):
Verify that `0 <= col_index < self.num_cols`.
Verify that `len(values) == len(self.entries)`.

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +    def add_rows(self, index_row_to_change, index_row_to_add):
Check correctness of `index_row_to_change` and `index_row_to_add`.

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +    def add_cols(self, index_col_to_change, index_col_to_add):
Check correctness of `index_col_to_change` and `index_col_to_add`.

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +        for i in range(self.num_cols):
Use `any(val != 0 for val in self.entries[entry_index])`.

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +                copied_row = copy(self.get_row(row_index))
Can we implement this without making copies? The cost of copying a list is O(n).

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +                copied_col = copy(self.get_col(col_index))
Can we implement this without making copies? The cost of copying a list is O(n).

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +            if value_check is True:
`if value_check:`

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +        """
Maybe we should add examples?

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +
Maybe we should add examples?

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +
Maybe we should add examples?

2021-12-12 11:58 UTC, besiobu commented on tda/matrix.py
> +        The method is not consistent with theory, but it is good enough
Explain why it works if it's not consistent with theory.

2022-11-20 14:54 UTC, AxelsFirst commented
Requested changes have been implemented.

2022-11-20 14:54 UTC, merged